name = "ai-shop-api"
main = "dist/worker.js"
compatibility_date = "2024-01-01"

[vars]
# Override in Cloudflare Dashboard if needed

[[d1_databases]]
binding = "DB"
database_name = "ai-shop-db"
database_id = "3992f50a-992e-439f-b2ad-8863b54b8b94"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "ai-shop-uploads"
